meta = {
    "sk": {
        "name": "Tibor Modroczky",
        "title": "Servis a predaj výpočtovej techniky a spotrebnej elektroniky",
        "description": "Oprava TV, PC, notebookov, audio a video zariadení, autokľúčov, predaj antivírusu Eset, inštalácia, údržba počítačov a notebookov, programovanie obvodov a iné.",
        "keywords": "opravy, oprava, servis, notebook, počítače, antivírus, NOD32, Eset, reflow, reballing, BGA obvody, inštalácia, servis, elektronika, LCD TV, TV, plasma, OLED, LCD, autokľúče, programovanie, obvody, audio, video, predaj, software, elektronika, zosilňovače, elektrónka, elektrónkový, údržba",
        "phone": "+421 905 460 506",
        "email": "modroczkyt@gmail.com",
        "address": {
            "name": "Tibor Modroczky",
            "street": "Diakovská 712",
            "postal": "925 01",
            "city": "Matúškovo",
        },
        "author": "Viktor Modroczký, Tibor Modroczky",
        "robots": "index, follow",
    },
    "hu": {
        "name": "Modroczky Tibor",
        "title": "Számítástechnikai és fogyasztói elektronika szervizelése és értékesítése",
        "description": "TV, PC, laptop, audio és video berendezések, autókulcsok javítása, Eset vírusirtó értékesítése, számítógépek és laptopok telepítése és karbantartása, áramkörök programozása és egyéb.",
        "keywords": "javítás, javítások, szerviz, laptop, számítógépek, vírusirtó, NOD32, Eset, reflow, reballing, BGA áramkörök, telepítés, szerviz, elektronika, LCD TV, TV, plazma, OLED, LCD, autókulcsok, programozás, áramkörök, audio, video, értékesítés, szoftverek, elektronika, erősítők, elektroncső, karbantartás",
        "phone": "+421 905 460 506",
        "email": "modroczkyt@gmail.com",
        "address": {
            "name": "Modroczky Tibor",
            "street": "Diakovská 712",
            "postal": "925 01",
            "city": "Matúškovo",
        },
        "author": "Viktor Modroczký, Tibor Modroczky",
        "robots": "index, follow",
    },
}

geo = {
    "latitude": 48.16455,
    "longitude": 17.74351,
}

intro = {
    "sk": [
        "Oprava a predaj elektroniky.",
        "Inštalácia softvéru a údržba počítačov.",
        "Programovanie pamätí a mikroprocesorov.",
    ],
    "hu": [
        "Elektronika javítása és értékesítése.",
        "Szoftver telepítése és a számítógépek karbantartása.",
        "Memóriák és mikroprocesszorok programozása.",
    ],
}

highlights = {
    "sk": [
        {
            "name": "Rýchlosť",
            "icon": "speedometer.svg",
            "description": "Naša prevádzka je profesionálne vybavená pre efektívne a rýchle opravy.",
        },
        {
            "name": "Skúsenosť",
            "icon": "list.svg",
            "description": "Máme za sebou tisícky opráv od začiatku svojho pôsobenia.",
        },
        {
            "name": "Eset Bronze Partner",
            "icon": "contract.svg",
            "description": "Sme súčasťou partnerského programu spoločnosti Eset pre predaj jej antivírusu.",
        },
    ],
    "hu": [
        {
            "name": "Gyorsaság",
            "icon": "speedometer.svg",
            "description": "Üzemünk professzionálisan felszerelt a hatékony és gyors javításokhoz.",
        },
        {
            "name": "Tapasztalat",
            "icon": "list.svg",
            "description": "Több ezer javítást végeztünk el a működésünk kezdete óta.",
        },
        {
            "name": "Eset Bronze Partner",
            "icon": "contract.svg",
            "description": "Az Eset antivírus értékesítésére vonatkozó partnerségi program része vagyunk.",
        },
    ],
}

gallery = {
    "sk": [
        {
            "name": "Infračervený spájkovací systém",
            "image": "bga.webp",
            "image_fallback": "bga.jpg",
        },
        {
            "name": "Teplovzdušná spájkovacia súprava",
            "image": "heater.webp",
            "image_fallback": "heater.jpg",
        },
        {
            "name": "Osciloskop a generátor priebehov",
            "image": "oscil.webp",
            "image_fallback": "oscil.jpg",
        },
        {
            "name": "Programátory obvodov",
            "image": "programmer.webp",
            "image_fallback": "programmer.jpg",
        },
        {
            "name": "Tester elektróniek",
            "image": "tester.webp",
            "image_fallback": "tester.jpg",
        },
    ],
    "hu": [
        {
            "name": "Infravörös forrasztórendszer",
            "image": "bga.webp",
            "image_fallback": "bga.jpg",
        },
        {
            "name": "Forrólevegős forrasztó készlet",
            "image": "heater.webp",
            "image_fallback": "heater.jpg",
        },
        {
            "name": "Oszcilloszkóp és jelgenerátor",
            "image": "oscil.webp",
            "image_fallback": "oscil.jpg",
        },
        {
            "name": "Áramkör programozók",
            "image": "programmer.webp",
            "image_fallback": "programmer.jpg",
        },
        {
            "name": "Elektroncső teszter",
            "image": "tester.webp",
            "image_fallback": "tester.jpg",
        },
    ],
}

actions = {
    "sk": [
        {
            "name": "Oprava spotrebnej elektroniky všetkých značiek",
            "image": "repair.webp",
            "image_fallback": "repair.jpg",
            "icon": "radio",
            "short_name": "Oprava elektroniky",
            "anchor": "oprava-spotrebnej-elektroniky",
            "items": [
                "oprava televízorov",
                "oprava satelitných prijímačov",
                "oprava monitorov",
                "oprava DVD prehrávačov a video zariadení",
                "oprava audio zariadení",
                "oprava elektrónkových zosilňovačov",
            ],
        },
        {
            "name": "Oprava notebookov",
            "image": "laptop.webp",
            "image_fallback": "laptop.jpg",
            "icon": "laptop_windows",
            "short_name": "Oprava notebookov",
            "anchor": "oprava-notebookov",
            "items": [
                "výmena displejov",
                "výmena klávesníc",
                "výmena napájacích konektorov",
                "oprava základných dosiek",
                "obnova poškodeného BIOS-u po neúspešnej aktualizácii",
                "výmena grafických kariet",
                "reflow (pretavenie) BGA obvodov",
                "reballing (preguličkovanie) a znovuosadenie BGA obvodov",
                "výmena alebo rozšírenie RAM",
                "výmena HDD a SSD",
                "diagnostika",
                "výmena teplovodivej pasty alebo teplovodivých podložiek",
                "zálohovanie a obnovenie dát",
            ],
        },
        {
            "name": "Oprava a údržba počítačov",
            "image": "pc.webp",
            "image_fallback": "pc.jpg",
            "icon": "desktop_windows",
            "short_name": "Oprava a údržba počítačov",
            "anchor": "oprava-pocitacov",
            "items": [
                "oprava základných dosiek",
                "oprava a výmena zdrojov",
                "výmena a rozšírenie komponentov",
                "obnova poškodeného BIOS-u po neúspešnej aktualizácii",
                "čistenie počítačov a notebookov od prachu a nečistôt",
                "prenesenie systému a súborov na nový disk",
                "výmena teplovodivej pasty",
            ],
        },
        {
            "name": "Oprava autokľúčov",
            "image": "car_keys.webp",
            "image_fallback": "car_keys.jpg",
            "icon": "key",
            "short_name": "Oprava autokľúčov",
            "anchor": "oprava-autoklucov",
            "items": [
                "výmena mikrospínačov",
                "výmena krytov a púzdier",
                "výmena batérií",
            ],
        },
        {
            "name": "Oprava vybraných modulov",
            "image": "module.webp",
            "image_fallback": "module.jpg",
            "icon": "memory",
            "short_name": "Oprava modulov",
            "anchor": "oprava-modulov",
            "items": [
                "moduly automatických brán",
                "moduly bielej techniky",
            ],
        },
        {
            "name": "Skladanie počítačov na mieru",
            "image": "custom_pc.webp",
            "image_fallback": "custom_pc.jpg",
            "icon": "build",
            "short_name": "Skladanie počítačov",
            "anchor": "skladanie-pocitacov",
            "items": [
                "herné alebo kancelárske zostavy",
                "výber vhodných komponentov podľa požiadaviek a rozpočtu zákazníka",
                "výber vhodných komponentov podľa katalógu hier alebo softvéru, ktorý zákazník používa",
            ],
        },
        {
            "name": "Inštalácia softvéru",
            "image": "sw.webp",
            "image_fallback": "sw.jpg",
            "icon": "terminal",
            "short_name": "Inštalácia softvéru",
            "anchor": "instalacia-softveru",
            "items": [
                "reinštalácia systému Windows",
                "inštalácia ovládačov",
                "inštalácia antivírusového programu ESET",
                "odvírenie systému",
                "záloha a obnova dát",
                "prenesenie systému a súborov na nový HDD alebo SSD",
                "diagnostika a údržba počítačov a notebookov",
            ],
        },
        {
            "name": "Programovanie obvodov",
            "image": "chip.webp",
            "image_fallback": "chip.jpg",
            "icon": "developer_board",
            "short_name": "Programovanie obvodov",
            "anchor": "programovanie-obvodov",
            "items": [
                "programovanie pamätí EPROM, EEPROM, Flash EPROM a sériových E(E)PROM rôznych typov",
                "programovanie mikroprocesorov Atmel, PIC atď...",
                "ponúkame aj možnosť odpájania a pripájania SMD obvodov",
            ],
        },
        {
            "name": "Predaj",
            "image": "build.webp",
            "image_fallback": "build.jpg",
            "icon": "store",
            "short_name": "Predaj",
            "anchor": "predaj",
            "items": [
                "predaj antivírusového programu ESET",
                "predaj repasovaných počítačov a notebookov",
                "dodanie náhradných zdrojov k notebookom rôznych značiek",
                "dodanie náhradných a originálnych diaľkových ovládačov pre TV, DVD, SAT",
                "na požiadanie dodávame aj iný tovar ako elektronické súčiastky, moduly, meniče, drobné náradie pre elektroniku, lupy, USB mikroskopy, spájkovačky, cín, atď...",
            ],
        },
    ],
    "hu": [
        {
            "name": "Minden márkájú fogyasztói elektronika javítása",
            "image": "repair.webp",
            "image_fallback": "repair.jpg",
            "icon": "radio",
            "short_name": "Elektronika javítása",
            "anchor": "oprava-spotrebnej-elektroniky",
            "items": [
                "televíziók javítása",
                "műholdvevők javítása",
                "monitorok javítása",
                "DVD-lejátszók és videoberendezések javítása",
                "audioberendezések javítása",
                "elektroncsöves erősítők javítása",
            ],
        },
        {
            "name": "Laptopok javítása",
            "image": "laptop.webp",
            "image_fallback": "laptop.jpg",
            "icon": "laptop_windows",
            "short_name": "Laptopok javítása",
            "anchor": "oprava-notebookov",
            "items": [
                "képernyők cseréje",
                "billentyűzetek cseréje",
                "tápcsatlakozók cseréje",
                "alaplapok javítása",
                "sérült BIOS helyreállítása sikertelen frissítés után",
                "grafikus kártyák cseréje",
                "BGA áramkörök újraolvasztása",
                "BGA áramkörök újragolyózása és újratelepítése",
                "RAM cseréje vagy bővítése",
                "HDD és SSD cseréje",
                "diagnosztika",
                "hővezető paszta vagy hővezető alátétek cseréje",
                "adatok biztonsági mentése és visszaállítása",
            ],
        },
        {
            "name": "Számítógépek javítása és karbantartása",
            "image": "pc.webp",
            "image_fallback": "pc.jpg",
            "icon": "desktop_windows",
            "short_name": "PC javítás és karbantartás",
            "anchor": "oprava-pocitacov",
            "items": [
                "alaplapok javítása",
                "tápegységek javítása és cseréje",
                "komponensek cseréje és bővítése",
                "sérült BIOS helyreállítása sikertelen frissítés után",
                "számítógépek és laptopok tisztítása portól és szennyeződésektől",
                "rendszer és fájlok áthelyezése új meghajtóra",
                "hővezető paszta cseréje",
            ],
        },
        {
            "name": "Autókulcsok javítása",
            "image": "car_keys.webp",
            "image_fallback": "car_keys.jpg",
            "icon": "key",
            "short_name": "Autókulcsok javítása",
            "anchor": "oprava-autoklucov",
            "items": [
                "mikrokapcsolók cseréje",
                "burkolatok és tokok cseréje",
                "elemek cseréje",
            ],
        },
        {
            "name": "Kiválasztott modulok javítása",
            "image": "module.webp",
            "image_fallback": "module.jpg",
            "icon": "memory",
            "short_name": "Modulok javítása",
            "anchor": "oprava-modulov",
            "items": [
                "automatikus kapuk moduljai",
                "háztartási gépek moduljai",
            ],
        },
        {
            "name": "Egyedi számítógépek összeszerelése",
            "image": "custom_pc.webp",
            "image_fallback": "custom_pc.jpg",
            "icon": "build",
            "short_name": "PC összeszerelése",
            "anchor": "skladanie-pocitacov",
            "items": [
                "játék- vagy irodai konfigurációk",
                "megfelelő komponensek kiválasztása az ügyfél igényei és költségvetése alapján",
                "megfelelő komponensek kiválasztása a játékok vagy szoftverek katalógusa alapján, amelyeket az ügyfél használ",
            ],
        },
        {
            "name": "Szoftver telepítése",
            "image": "sw.webp",
            "image_fallback": "sw.jpg",
            "icon": "terminal",
            "short_name": "Szoftver telepítése",
            "anchor": "instalacia-softveru",
            "items": [
                "Windows rendszer újratelepítése",
                "illesztőprogramok telepítése",
                "ESET vírusirtó program telepítése",
                "rendszer vírusmentesítése",
                "adatok biztonsági mentése és visszaállítása",
                "rendszer és fájlok áthelyezése új HDD-re vagy SSD-re",
                "számítógépek és laptopok diagnosztikája és karbantartása",
            ],
        },
        {
            "name": "Áramkörök programozása",
            "image": "chip.webp",
            "image_fallback": "chip.jpg",
            "icon": "developer_board",
            "short_name": "Áramkörök programozása",
            "anchor": "programovanie-obvodov",
            "items": [
                "különböző típusú EPROM, EEPROM, Flash EPROM és soros E(E)PROM memóriák programozása",
                "Atmel, PIC stb. mikroprocesszorok programozása",
                "lehetőséget kínálunk SMD áramkörök forrasztására és leszerelésére is",
            ],
        },
        {
            "name": "Értékesítés",
            "image": "build.webp",
            "image_fallback": "build.jpg",
            "icon": "store",
            "short_name": "Értékesítés",
            "anchor": "predaj",
            "items": [
                "ESET antivírus program értékesítése",
                "felújított számítógépek és laptopok értékesítése",
                "különböző márkájú laptopokhoz tartozó pótalkatrészek szállítása",
                "TV, DVD, SAT távirányítók pótalkatrészeinek szállítása igény szerint, beleértve más árukat is, például elektronikai alkatrészeket, modulokat, átalakítókat, apró elektronikai szerszámokat, nagyítókat, USB mikroszkópokat, forrasztópákákat, ónokat stb.",
            ],
        },
    ],
}


text = {
    "sk": {
        "show_coordinates": "Zobraziť zemepisnú šírku a dĺžku",
        "latitude": "Šírka",
        "longitude": "Dĺžka",
        "open_in_google_maps": "Otvoriť v Google Maps",
        "contact_info": "Kontaktné informácie",
        "call_mobile": "Zavolať na mobil",
        "share_us": "Zdieľajte nás",
        "send_email": "Poslať e-mail",
        "back_to_top": "Prejsť na začiatok",
        "collapse_gallery": "Skryť galériu výbavy",
        "expand_gallery": "Rozbaliť galériu výbavy",
        "about_us": "Váš spoľahlivý a férový servis so skúsenosťami od roku 1994.",
        "details": "Podrobnosti",
        "feedback": "Spätná väzba k stránke",
        "contact": "Kontakt",
        "top_image_alt": "Plošný spoj",
    },
    "hu": {
        "show_coordinates": "Földrajzi szélesség és hosszúság megjelenítése",
        "latitude": "Szélesség",
        "longitude": "Hosszúság",
        "open_in_google_maps": "Megnyitás a Google Térképen",
        "contact_info": "Kapcsolattartási információk",
        "call_mobile": "Hívás a mobilra",
        "share_us": "Ajánljon minket",
        "send_email": "E-mail küldése",
        "back_to_top": "Vissza a tetejére",
        "collapse_gallery": "A galéria elrejtése",
        "expand_gallery": "A galéria kibontása",
        "about_us": "Megbízható és tisztességes szerviz tapasztalattal 1994 óta.",
        "details": "Részletek",
        "feedback": "Visszajelzés az oldalhoz",
        "contact": "Kapcsolat",
        "top_image_alt": "Nyomtatott áramkör",
    },
}
